name: Cobol CI/CD Pipeline

on:
    push:
        branches:
        - main

env:
  BINARY_NAME: CBACT01C #test

jobs:
  build-artifacts:
    runs-on: cobol
    steps:
      - name: Checkout Main Repository    #¿Utilizar sparse-checkout para bajarse ficheros determinados, como Copybooks?
        uses: actions/checkout@v2
      # - name: Determine changed files and update binary versions
      #   run: |
      #     cd ${{ github.workspace }}/${{ env.REPO_NAME }}/cicd_scripts/
      #     chmod +x ./git-diif.sh

      - name: Extract Binary version
        id: output_version
        env:
          BINARY_NAME: CBACT01C #test
        run: |
          VERSION=$(yq e '.binaries[] | select(.name == "$BINARY_NAME").version' ./artifacts_version.yml)
          echo "Binary version: $VERSION"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo $GITHUB_ENV

