name: Cobol CI/CD Pipeline

on:
    push:
        branches:
        - main

jobs:
  build-artifacts:
    runs-on: cobol
    steps:
      - name: Checkout Main Repository    #¿Utilizar sparse-checkout para bajarse ficheros determinados, como Copybooks?
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Determine changed files and update binary versions
        run: |
          cd cicd_scripts/
          chmod +x git-diff.sh
          ./git-diff.sh

      - name: Stage Changes
        run: git add .
  
      - name: Commit Changes
        run: git commit -m "Automated updated artifacts_version.yaml by GitHub Actions workflow"
  
      - name: Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git push https://davidruedasalas:${{ secrets.GH_PAT }}@github.com/davidcambrils25/cobol-test.git

      - name: Extract Binary version
        id: output_version
        env:
          BINAR_NAME: CBA #test
        run: |
          echo ${{ env.BINARY_NAME }}
          VERSION=$(yq e '.binaries[] | select(.name == "${{ env.BINARY_NAME }}").version' ./artifacts_version.yml)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Binary version: $VERSION"
          echo $GITHUB_ENV

