name: Cobol CI/CD Pipeline

on:
    push:
        branches:
        - main

jobs:
  build-artifacts:
    runs-on: cobol
    steps:
      - name: Checkout Main Repository    #¿Utilizar sparse-checkout para bajarse ficheros determinados, como Copybooks?
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Determine changed files and update binary versions
        run: |
          cd cicd_scripts/
          chmod +x git-diff.sh
          ./git-diff.sh
      
      - name: Set up Git
        run: |
          git config --global user.name "davidruedasalas"
          git config --global user.email "davidruedasalas@gmail.com"

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code -- ./artifacts_version.yaml
          if [ $? -eq 1 ]; then
            echo "CHANGES_FOUND=true" >> $GITHUB_ENV
          else
            echo "CHANGES_FOUND=false" >> $GITHUB_ENV
          fi
        
      - name: Commit changes
        if: env.CHANGES_FOUND == 'true'
        run: |
          git add ./artifacts_version.yaml
          git commit -m "Automated updated artifacts_version.yaml by GitHub Actions workflow"
          git push https://davidruedasalas:${{ secrets.GH_PAT }}@github.com/davidcambrils25/cobol-test.git

      - name: Extract Binary version
        id: output_version
        run: |
          echo ${{ env.BINARY_NAME }}
          echo "Binary version to deploy: ${{ env.NEW_VERSION }}


#VERSION=$(yq e ".binaries[] | select(.name == \"$BINARY_NAME\") | .versions[] | select(.version == \"$NEW_VERSION\")" ./artifacts_version.yml)#