name: Cobol CI/CD Pipeline

on:
    push:
        branches:
        - main

env:
  BINARY_NAME: CBACT01C #test

jobs:
  build-artifacts:
    runs-on: cobol
    steps:
      - name: Checkout Main Repository    #¿Utilizar sparse-checkout para bajarse ficheros determinados, como Copybooks?
        uses: actions/checkout@v2
      - name: Determine changed files and update binary versions
        run: |
          cd /cicd_scripts/
          chmod +x git-diff.sh
          ./git-diff.sh "${{ env.BINARY_NAME }}"

      # - name: Extract Binary version
      #   id: output_version
      #   env:
      #     BINAR_NAME: CBA #test
      #   run: |
      #     VERSION=$(yq e '.binaries[] | select(.name == "${{ env.BINARY_NAME }}").version' ./artifacts_version.yml)
      #     echo "VERSION=${VERSION}" >> $GITHUB_ENV
      #     echo "Binary version: $VERSION"
      #     echo $GITHUB_ENV
      #     echo $BINAR_NAME

